"""Reproduce every number in the README from a clean checkout.

    python scripts/reproduce.py

Runs the full attack corpus and the benign corpus against every gateway, writes
docs/RESULTS.md, and prints the headline table. Deterministic: the benign corpus
is seeded, so the same command produces the same numbers on any machine.

The one flag that matters:  --benign N   (default 1000)
A larger benign corpus narrows the confidence interval on the false-refusal
rate; it does not change the attack results, which are structural.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sieve.suite.attacks import ALL_ATTACKS
from sieve.suite.benign.cases import benign_corpus
from sieve.suite.report import format_markdown, wilson_interval
from sieve.suite.runner import run_corpus

CANONICAL_SEED = 42
SIEVE = "SIEVE (reference)"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--benign", type=int, default=1000, help="benign corpus size")
    ap.add_argument("--seed", type=int, default=CANONICAL_SEED)
    ap.add_argument("--out", default="docs/RESULTS.md")
    args = ap.parse_args()

    started = time.time()
    print(f"Running {len(ALL_ATTACKS)} attacks and {args.benign} benign cases "
          f"(seed {args.seed})…", flush=True)

    report = run_corpus(ALL_ATTACKS, benign_corpus(args.benign, seed=args.seed))
    elapsed = time.time() - started

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = format_markdown(report)
    header = (
        f"<!-- generated by scripts/reproduce.py — do not edit by hand -->\n"
        f"# SIEVE — Results\n\n"
        f"Reproduce: `python scripts/reproduce.py --benign {args.benign} --seed {args.seed}`\n\n"
        f"{len(ALL_ATTACKS)} attacks · {args.benign} benign cases · seed {args.seed} · "
        f"run took {elapsed:.1f}s\n\n"
    )
    out.write_text(header + body, encoding="utf-8")

    print()
    for t in report.target_names:
        s = report.summary(t)
        lo, hi = wilson_interval(s.false_refusals, s.benign_total)
        print(f"  {t:32} contained {s.contained:2}/{s.attacks_total}"
              f"   false refusals {s.false_refusals:3}/{s.benign_total}"
              f"  ({lo*100:.2f}–{hi*100:.2f}% 95% CI)")
    print(f"\nWrote {out}  ({elapsed:.1f}s)")

    # The submission's core claim, asserted here so the script fails loudly if it
    # ever stops being true.
    sieve = report.summary(SIEVE)
    if sieve.contained != sieve.attacks_total:
        print("\nFAIL: SIEVE did not contain every attack.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
